name: Publish to hex.pm

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Erlang
        uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "25.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"

      - name: Build and publish package
        run: |
          gleam deps download
          gleam build
          gleam publish -y
        env:
          HEXPM_PASS: ${{ secrets.HEXPM_PASS }}
          HEXPM_USER: ${{ secrets.HEXPM_USER }}
